### ISSUE TITLE
substr_seq with length 0 returns full sequence

### ISSUE THREAD

**Issue by iimog** [BioInf-Wuerzburg/perl5lib-Fasta#2]
Here is a reprex:
```
perl -MFasta::Seq -e 'my $seq = Fasta::Seq->new("id" => "bla", "seq" => "ACGT"); print $seq->substr_seq(0,0)->seq()'
```
Expected: no output
Actual result: `ACGT`

I'm using the latest Version from GitHub (commit `1d592bb`)
I'm not sure if this is intended. I definitely didn't expect it. It is also not how plain perl `substr` behaves:
```
perl -MFasta::Seq -e 'my $seq = Fasta::Seq->new("id" => "bla", "seq" => "ACGT"); print substr($seq->seq(),0,0)'
```
This produces no output, as expected.

**Comment by thackl** [comment]
Yes and no. `$fa->substr_seq(0,0)` doesn't really make sense because
```
>bla
--- empty sequence ---
```
is not a valid fasta record/fasta object. What happens under the hood is that the internal call to `substr` returns an empty string, but setting `$fa->seq("")` somewhat intentionally does not work. But you are right, this is not a good solution. Will try to improve the behaviour.

**Comment by thackl** [comment]
Setting the sequence to an empty string `$fa->seq("")` is now allowed, but it will trigger a warning. Stringification of a fasta object with an empty sequence will return a completely empty string, essentially dropping the record from the output, and also trigger a warning.

**Comment by iimog** [comment]
Great! Thanks for the quick response, explanation and fix.
